version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:7009@db:5432/test?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7009
      POSTGRES_DB: test
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
