# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to EC2
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${EC2_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-34-207-53-0.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        ssh -i "~/.ssh/id_rsa" ubuntu@ec2-34-207-53-0.compute-1.amazonaws.com << 'EOF'
        sudo tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
        source ~/.profile  # or ~/.bashrc or ~/.zshrc
        cd user_api_unit-testing/
        pkill -f project || true
        git pull
        go build
        nohup ./project > app.log 2>&1 &
        exit
        EOF
